name: Flutter Auto Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Placeholder Config
        run: |
          mkdir -p lib/config
          echo "class MidtransConfig { static const String merchantId = ''; static const String serverKey = ''; static const String clientKey = ''; }" > lib/config/midtrans_config.dart

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'

      - name: Install Dependencies
        run: flutter pub get

      - name: Decode Keystore
        shell: python
        run: |
          import os
          import base64
          keystore_base64 = os.environ['KEYSTORE_BASE64']
          with open("android/app/release-keystore.jks", "wb") as f:
              f.write(base64.b64decode(keystore_base64))
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Build APK
        run: flutter build apk --release
        env:
          STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_FILE: release-keystore.jks

      - name: Read Version
        id: version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Dapoer POS v${{ env.VERSION }}
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}